### ISSUE TITLE
Release Modpack on Modrinth

### ISSUE THREAD

**Issue by Akasiek** [VazkiiMods/Musketeer#8]
Hi!
Is there any way this modpack could be published on Modrinth? Many people nowadays prefer Modrinth over Curse.

**Comment by EzioTheDeadPoet** [comment]
I mean you can still install it with any launcher. 🤔
I for example used Prism Launcher to install it.

**Comment by Akasiek** [comment]
I'm trying to use Modrinth own launcher and they only provide Modrinth modpacks. But no pressure. I'm just asking if it is possible.

**Comment by EzioTheDeadPoet** [comment]
Fair. But I think it might be a lot harder since a lot of mods seem to come from Curse and at least some are bound to not have Modrinth versions. And if they already don't allow importing of curse packs in their launcher then they probably don't support mods from there. 

So personally I think this is more an issue for the Modrinth Launcher then.
Also I am saying this as someone who personally prefers looking for mods on Modrinth than on Curse. And the only mod I ever made for Minecraft (I usually mod Skyrim a lot, or at least did) that actually was more of an adaptation of another mods API, is only uploaded on GitHub and Modrinth.

**Comment by Akasiek** [comment]
You have a great point. I've never looked on it that way. Thank you for your help.
